//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InternetBankingDal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Accounts
    {
        public Accounts()
        {
            this.Cards = new HashSet<Cards>();
            this.ClientRemittances = new HashSet<ClientRemittances>();
            this.Credit = new HashSet<Credit>();
            this.Deposit = new HashSet<Deposit>();
            this.PaymentCompanies = new HashSet<PaymentCompanies>();
        }
    
        public System.Guid AccountId { get; set; }
        public System.Guid UserId { get; set; }
        public string Number { get; set; }
        public int Type { get; set; }
        public decimal Ammount { get; set; }
        public int Currency { get; set; }
        public System.DateTime StartDate { get; set; }
        public Nullable<decimal> OverdraftLimit { get; set; }
    
        public virtual ICollection<Cards> Cards { get; set; }
        public virtual ICollection<ClientRemittances> ClientRemittances { get; set; }
        public virtual ICollection<Credit> Credit { get; set; }
        public virtual ICollection<Deposit> Deposit { get; set; }
        public virtual ICollection<PaymentCompanies> PaymentCompanies { get; set; }
        public virtual aspnet_Users aspnet_Users { get; set; }
    }
}
