//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InternetBankingDal
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountOperations
    {
        public AccountOperations()
        {
            this.ClientRemittances = new HashSet<ClientRemittances>();
            this.Remittances = new HashSet<Remittances>();
        }
    
        public System.Guid AccountOperationId { get; set; }
        public string AccountNumber { get; set; }
        public int Type { get; set; }
        public string Description { get; set; }
        public System.DateTime OperationDate { get; set; }
        public decimal Ammount { get; set; }
        public Nullable<int> Currency { get; set; }
        public decimal Balance { get; set; }
    
        public virtual ICollection<ClientRemittances> ClientRemittances { get; set; }
        public virtual ICollection<Remittances> Remittances { get; set; }
    }
}
