//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InternetBankingDal
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountOperations
    {
        public System.Guid AccountOperationId { get; set; }
        public string AccountNumber { get; set; }
        public int Type { get; set; }
        public string Description { get; set; }
        public System.DateTime OperationDate { get; set; }
        public decimal Ammount { get; set; }
        public Nullable<int> Currency { get; set; }
        public decimal Balance { get; set; }
    }
}
