//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InternetBankingDal
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdditionalUserData
    {
        public System.Guid Id { get; set; }
        public System.Guid UserId { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public System.DateTime BirthDate { get; set; }
        public string Nationality { get; set; }
        public string IdentificationNumber { get; set; }
        public string PassportNumber { get; set; }
        public bool IsTemporary { get; set; }
    
        public virtual aspnet_Users aspnet_Users { get; set; }
    }
}
