//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InternetBankingDal
{
    using System;
    using System.Collections.Generic;
    
    public partial class CardOperations
    {
        public System.Guid CardOperationId { get; set; }
        public System.Guid CardId { get; set; }
        public int Type { get; set; }
        public System.DateTime OperationDate { get; set; }
        public string Description { get; set; }
        public decimal Amount { get; set; }
        public int Currency { get; set; }
        public decimal AmountAccountCurrency { get; set; }
        public decimal StartBalance { get; set; }
    
        public virtual Cards Cards { get; set; }
    }
}
