//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InternetBankingDal
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientRemittancesTemplates
    {
        public System.Guid ClientRemittancesTemplateId { get; set; }
        public byte[] StartAccountNumber { get; set; }
        public string EndAccountNumber { get; set; }
        public string Name { get; set; }
        public string RecipientName { get; set; }
        public int Type { get; set; }
        public decimal Ammount { get; set; }
        public int Currency { get; set; }
    }
}
