//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InternetBankingDal
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConvertationTemplates
    {
        public System.Guid ConvertationTemplateId { get; set; }
        public string Name { get; set; }
        public string StartAccountName { get; set; }
        public string EndAccountName { get; set; }
        public decimal Amount { get; set; }
        public int Currency { get; set; }
    }
}
