//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InternetBankingDal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Convertations
    {
        public System.Guid ConvertationId { get; set; }
        public System.Guid OperationId { get; set; }
        public System.Guid EndAccountId { get; set; }
        public int Currency { get; set; }
        public double Cource { get; set; }
    }
}
