//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InternetBankingDal
{
    using System;
    using System.Collections.Generic;
    
    public partial class CreditOperations
    {
        public System.Guid CreditOperationId { get; set; }
        public System.Guid CreditId { get; set; }
        public int Type { get; set; }
        public System.DateTime OperationDate { get; set; }
        public decimal Amount { get; set; }
        public int Currency { get; set; }
    }
}
