//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InternetBankingDal
{
    using System;
    using System.Collections.Generic;
    
    public partial class CreditOperations
    {
        public System.Guid CreditOperationId { get; set; }
        public System.Guid CreditId { get; set; }
        public int Type { get; set; }
        public System.DateTime OperationDate { get; set; }
        public decimal Amount { get; set; }
        public int Currency { get; set; }
    
        public virtual Credit Credit { get; set; }
    }
}
