//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InternetBankingDal
{
    using System;
    using System.Collections.Generic;
    
    public partial class CreditPayments
    {
        public System.Guid CreditPaymentId { get; set; }
        public decimal Debt { get; set; }
        public decimal OutDebt { get; set; }
        public decimal Percents { get; set; }
        public decimal Reward { get; set; }
        public decimal Fine { get; set; }
        public int Currency { get; set; }
    }
}
