//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InternetBankingDal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Deposit
    {
        public System.Guid DepositId { get; set; }
        public string Number { get; set; }
        public int Type { get; set; }
        public decimal Ammount { get; set; }
        public decimal StartAmmount { get; set; }
        public int Currency { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public double InterestRate { get; set; }
        public System.Guid AccountId { get; set; }
        public System.Guid CallbackAccountId { get; set; }
        public bool AutoContinue { get; set; }
    }
}
