//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InternetBankingDal
{
    using System;
    using System.Collections.Generic;
    
    public partial class DepositOperations
    {
        public System.Guid DepositOperationId { get; set; }
        public System.Guid DepositId { get; set; }
        public int Type { get; set; }
        public System.DateTime OperationDate { get; set; }
        public string Description { get; set; }
        public decimal Amount { get; set; }
        public decimal EndBalance { get; set; }
    
        public virtual Deposit Deposit { get; set; }
    }
}
