//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InternetBankingDal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Deposit
    {
        public Deposit()
        {
            this.DepositOperations = new HashSet<DepositOperations>();
        }
    
        public System.Guid DepositId { get; set; }
        public string Number { get; set; }
        public int Type { get; set; }
        public decimal Ammount { get; set; }
        public decimal StartAmmount { get; set; }
        public int Currency { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public double InterestRate { get; set; }
        public System.Guid AccountId { get; set; }
        public System.Guid CallbackAccountId { get; set; }
        public bool AutoContinue { get; set; }
    
        public virtual Accounts Accounts { get; set; }
        public virtual ICollection<DepositOperations> DepositOperations { get; set; }
    }
}
