//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InternetBankingDal
{
    using System;
    using System.Collections.Generic;
    
    public partial class DepositOperations
    {
        public System.Guid DepositOperationId { get; set; }
        public System.Guid DepositId { get; set; }
        public int Type { get; set; }
        public System.DateTime OperationDate { get; set; }
        public string Description { get; set; }
        public decimal Amount { get; set; }
        public decimal EndBalance { get; set; }
    }
}
