//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InternetBankingDal
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentCompanies
    {
        public PaymentCompanies()
        {
            this.Payments = new HashSet<Payments>();
        }
    
        public System.Guid PaymentCompanyId { get; set; }
        public System.Guid AccountId { get; set; }
        public string Name { get; set; }
    
        public virtual Accounts Accounts { get; set; }
        public virtual ICollection<Payments> Payments { get; set; }
    }
}
