//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InternetBankingDal
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentTemplates
    {
        public System.Guid PaymentTemplateId { get; set; }
        public string AccountNumber { get; set; }
        public string PaymentCompanyName { get; set; }
        public decimal Amount { get; set; }
        public string CompanyClientIdentity { get; set; }
        public string Inforamation { get; set; }
    }
}
