//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InternetBankingDal
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentTemplates
    {
        public System.Guid PaymentTemplateId { get; set; }
        public string AccountNumber { get; set; }
        public string PaymentCompanyName { get; set; }
        public decimal Amount { get; set; }
        public string CompanyClientIdentity { get; set; }
        public string Inforamation { get; set; }
    }
}
