//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InternetBankingDal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payments
    {
        public System.Guid PaymentId { get; set; }
        public System.Guid OperationId { get; set; }
        public System.Guid PaymentCompanyId { get; set; }
        public string CompanyClientIdentity { get; set; }
        public string Inforamation { get; set; }
    }
}
