//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InternetBankingDal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payments
    {
        public System.Guid PaymentId { get; set; }
        public System.Guid OperationId { get; set; }
        public System.Guid PaymentCompanyId { get; set; }
        public string CompanyClientIdentity { get; set; }
        public string Inforamation { get; set; }
    
        public virtual PaymentCompanies PaymentCompanies { get; set; }
    }
}
