//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InternetBankingDal
{
    using System;
    using System.Collections.Generic;
    
    public partial class RemittanceTemplates
    {
        public System.Guid RemittanceTemplateId { get; set; }
        public string Name { get; set; }
        public string StartAccountNumber { get; set; }
        public string EndAccountNumber { get; set; }
        public decimal Amount { get; set; }
        public int Currency { get; set; }
    }
}
