//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InternetBankingDal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Remittances
    {
        public System.Guid RemittanceId { get; set; }
        public System.Guid EndAccount { get; set; }
        public System.Guid AccountOperationId { get; set; }
    
        public virtual AccountOperations AccountOperations { get; set; }
    }
}
