//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InternetBankingDal
{
    using System;
    using System.Collections.Generic;
    
    public partial class RemittanceTemplates
    {
        public System.Guid RemittanceTemplateId { get; set; }
        public string Name { get; set; }
        public string StartAccountNumber { get; set; }
        public string EndAccountNumber { get; set; }
        public decimal Amount { get; set; }
        public int Currency { get; set; }
    }
}
